---
- hosts: webservers
  become: yes
  tasks:
  - name: install webserver(apache2) on ubuntu20 node1
    apt:
     name: apache2
     state: present
    when: ansible_os_family == "Debian"

  - name: start the apache2 service
    service:
     name: apache2
     state: started
    when: ansible_os_family == "Debian" 
