--- 
- name: installing s/w packages
  hosts: webserver
  tasks:
  - name: install packages
    apt:
     name: "{{item}}"
     state: present
     update_cache: yes
    with_items:
     - git
     - tree
